library(plumber)
library(calendar)
library(dplyr)
library(stringr)
library(lubridate)
library(calendar)
library(glue)
library(ScreenShot2CalendarEndpoint)
# plumber.R

#* Echo the parameter that was sent in
#* @param msg The message to echo back.
#* @param event_title Title of the event
#* @get /echo
function(msg=""){
  list(msg = paste0("The message is: '", msg, "'"))
}

#* Convert the input image to an ical event
#* @param img_file:file the screenshot
#* @param event_title:str title of the event
#* @post /schedule
#* @serializer text
function(img_file, event_title = "TT Reservoir (autogenerated)"){

  ## save the file for access
  tmp <- tempfile("plumb", fileext = paste0("_", basename(names(img_file))))
  on.exit(unlink(tmp))
  writeBin(img_file[[1]], tmp)
  
  text <- extract_text(tmp)

  week_ <- text %>% 
    str_split_1("\n") %>% 
    get_week()

  shifts <- text %>% 
      str_split_1("\n") %>% 
      get_shifts()

  shifts %>%
      mutate(start_of_week = ymd(week_[[1]])) %>%
      rowwise() %>% 
      mutate(shift = paste0(c(day, date, month(start_of_week), year(start_of_week)), collapse=" ")) %>%
      mutate(start_processed = paste0(c(shift, start), collapse = " "), end_processed = paste0(c(shift, end), collapse = " ")) %>%
      mutate(start_processed = dmy_hm(start_processed, tz = "America/New_York"), end_processed = dmy_hm(end_processed, tz = "America/New_York")) %>%
      ungroup() -> processed_shifts

  icals <- c()

  for(l in 1:nrow(processed_shifts)) {
      

      icals[[l]] <-  

          ic_event(
              start_time = processed_shifts$start_processed[l],
              end_time = processed_shifts$end_processed[l],

              summary = glue("{event_title}\n\n{processed_shifts$shift[l]} from {processed_shifts$start[l]} to {processed_shifts$end[l]}. \n\nAutogenerated {now()}"),
              
          )
  }

  bind_rows(icals) %>%
    ic_character() %>%
    paste0(collapse = "\n") -> ic
  
  print(text)
  print(week_)
  print(shifts)
  print(ic)
  print(bind_rows(icals))

  as_attachment(ic, "output.ics")

}

# run with pr("plumber.R") %>% pr_run(port=8080)