---
title: "flat_additional.Rmd Core Functionality"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(tesseract)
library(lubridate)
library(dplyr)
library(stringr)
library(purrr)
library(glue)
library(calendar)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# extract_text

This function extracts lines of text from a schedule screenshot 

```{r function-extract_text}
#' extract_text
#' 
#' @description
#' Extract text from a screenshot image
#'
#' @param img_file Screenshot of the schedule for the week
#' @importFrom tesseract tesseract ocr
#' @return Text extracted from the screenshot
#' @export
extract_text <- function(img_file) {
  
  eng <- tesseract("eng")
  text <- ocr(img_file, engine = eng)

  text
}
```

```{r examples-extract_text}
img_file <- system.file("testdata/IMG_0579.PNG", package = "ScreenShot2CalendarEndpoint")
extract_text(img_file)
```

```{r tests-extract_text}
test_that("extract_text works", {
  expect_true(is.character(extract_text(system.file("testdata/IMG_0579.PNG", package = "ScreenShot2CalendarEndpoint"))))
})
```

# get_week
    
```{r function-get_week}
#' get_week
#' 
#' Description
#' 
#' Get the week start and end dates from the converted text
#' 
#' @param lines Lines extracted from \code{\link{extract_text}}
#' @importFrom stringr str_split_1
#' @importFrom lubridate dmy
#' @return Start and end dates of the week
#' 
#' @export
get_week <- function(lines){
    
    tryCatch(
        {
            dateline <- lines[3]

            dateline %>% 
                str_split_1(pattern = " - ") %>%
                dmy()
        },

        error = function(cond) {
            message("Error parsing week of shift")
            message("Here's the original error message:")
            message(conditionMessage(cond))
            # Choose a return value in case of error
            stop()
        }
    )
}
```
  

```{r example-get_week}
#' \dontrun{
#' img_file <- system.file("testdata/IMG_0579.PNG", package = "ScreenShot2CalendarEndpoint")
#' text <- extract_text(img_file)
#' text %>% 
#'   str_split_1("\n") %>% 
#'   get_week()
#' }

```
  
```{r tests-get_week}
test_that("get_week works", {
  expect_length({

    img_file <- system.file("testdata/IMG_0579.PNG", package = "ScreenShot2CalendarEndpoint")

    text <- extract_text(img_file)

    text %>% 
      str_split_1("\n") %>% 
      get_week()

  }, n = 2) 
})
```

# get_shifts
    
```{r function-get_shifts}
#' get_shifts
#' 
#' Description
#' 
#' Get each shift in a tidy format
#' 
#' @param lines Lines extracted from \code{\link{extract_text}}
#' @importFrom stringr str_split_1 str_detect
#' @importFrom purrr pluck compact
#' @importFrom dplyr bind_rows
#' @return Data frame where each row is a shift
#' 
#' @export
get_shifts <- function(lines) {

    shifts <- list()

    for(l in seq_along(lines)){

        if(str_detect(lines[l], "Regular")){

            # print(lines[l]) # shift detected
            # print(lines[l+1]) # date and time

            day_of_shift <- lines[l] %>%
                str_split_1(., " +") %>%
                pluck(1)

            date_of_shift <- lines[l+1] %>%
                str_split_1(., " +") %>%
                pluck(1)

            start_time <- lines[l+1] %>%
                str_split_1(., " +") %>%
                pluck(2) %>%
                str_split_1(., "-") %>%
                pluck(1)

            end_time <- lines[l+1] %>%
                str_split_1(., " +") %>%
                pluck(2) %>%
                str_split_1(., "-") %>%
                pluck(2)

            shifts[[l]] <- c(day = day_of_shift, date = date_of_shift, start = start_time, end = end_time)
        
        }
    }

    shifts <- compact(shifts)

    return(bind_rows(shifts))
}
```
  


```{r example-get_shifts}
#' \dontrun{text %>% 
#'     str_split_1("\n") %>% 
#'     get_shifts()}
```
  
```{r tests-get_shifts}
test_that("get_shifts works", {
  expect_true({

    img_file <- system.file("testdata/IMG_0579.PNG", package = "ScreenShot2CalendarEndpoint")

    text <- extract_text(img_file)

    shifts <- text %>% 
      str_split_1("\n") %>% 
      get_shifts()

    nrow(shifts) == 3

  }) 
})
```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_additional.Rmd", vignette_name = "Core Functionality")
```

