# WARNING - Generated by {fusen} from dev/flat_additional.Rmd: do not edit by hand

test_that("get_shifts works", {
  expect_true({

    img_file <- system.file("testdata/IMG_0579.PNG", package = "ScreenShot2CalendarEndpoint")

    text <- extract_text(img_file)

    shifts <- text %>% 
      str_split_1("\n") %>% 
      get_shifts()

    nrow(shifts) == 3

  }) 
})
