# WARNING - Generated by {fusen} from dev/flat_additional.Rmd: do not edit by hand

test_that("extract_text works", {
  expect_true(is.character(extract_text(system.file("testdata/IMG_0579.PNG", package = "ScreenShot2CalendarEndpoint"))))
})
