# WARNING - Generated by {fusen} from dev/flat_additional.Rmd: do not edit by hand

#' extract_text
#' 
#' @description
#' Extract text from a screenshot image
#'
#' @param img_file Screenshot of the schedule for the week
#' @importFrom tesseract tesseract ocr
#' @return Text extracted from the screenshot
#' @export
#' @examples
#' img_file <- system.file("testdata/IMG_0579.PNG", package = "ScreenShot2CalendarEndpoint")
#' extract_text(img_file)
extract_text <- function(img_file) {
  
  eng <- tesseract("eng")
  text <- ocr(img_file, engine = eng)

  text
}
