# WARNING - Generated by {fusen} from dev/flat_additional.Rmd: do not edit by hand

#' my_fun extract_text
#'
#' @return 1
#' @export
#'
#' @examples
#' img_file <- system.file("testdata/IMG_0579.PNG", package = "ScreenShot2CalendarEndpoint")
#' extract_text(img_file)
extract_text <- function(img_file) {
  
  eng <- tesseract::tesseract("eng")
  text <- tesseract::ocr(img_file, engine = eng)

  text
}
