# WARNING - Generated by {fusen} from dev/flat_additional.Rmd: do not edit by hand

#' get_shifts
#' 
#' Description
#' 
#' Get each shift in a tidy format
#' 
#' @param lines Lines extracted from \code{\link{extract_text}}
#' @importFrom stringr str_split_1 str_detect
#' @importFrom purrr pluck compact
#' @importFrom dplyr bind_rows
#' @return Data frame where each row is a shift
#' 
#' @export
#' @examples
#' \dontrun{text %>% 
#'     str_split_1("\n") %>% 
#'     get_shifts()}
get_shifts <- function(lines) {

    shifts <- list()

    for(l in seq_along(lines)){

        if(str_detect(lines[l], "Regular")){

            # print(lines[l]) # shift detected
            # print(lines[l+1]) # date and time

            day_of_shift <- lines[l] %>%
                str_split_1(., " +") %>%
                pluck(1)

            date_of_shift <- lines[l+1] %>%
                str_split_1(., " +") %>%
                pluck(1)

            start_time <- lines[l+1] %>%
                str_split_1(., " +") %>%
                pluck(2) %>%
                str_split_1(., "-") %>%
                pluck(1)

            end_time <- lines[l+1] %>%
                str_split_1(., " +") %>%
                pluck(2) %>%
                str_split_1(., "-") %>%
                pluck(2)

            shifts[[l]] <- c(day = day_of_shift, date = date_of_shift, start = start_time, end = end_time)
        
        }
    }

    shifts <- compact(shifts)

    return(bind_rows(shifts))
}
