# WARNING - Generated by {fusen} from dev/flat_additional.Rmd: do not edit by hand

#' get_week
#' 
#' Description
#' 
#' Get the week start and end dates from the converted text
#' 
#' @param lines Lines extracted from \code{\link{extract_text}}
#' @importFrom stringr str_split_1
#' @importFrom lubridate dmy
#' @return Start and end dates of the week
#' 
#' @export
#' @examples
#' \dontrun{
#' img_file <- system.file("testdata/IMG_0579.PNG", package = "ScreenShot2CalendarEndpoint")
#' text <- extract_text(img_file)
#' text %>% 
#'   str_split_1("\n") %>% 
#'   get_week()
#' }
#'
get_week <- function(lines){
    
    tryCatch(
        {
            dateline <- lines[3]

            dateline %>% 
                str_split_1(pattern = " - ") %>%
                dmy()
        },

        error = function(cond) {
            message("Error parsing week of shift")
            message("Here's the original error message:")
            message(conditionMessage(cond))
            # Choose a return value in case of error
            stop()
        }
    )
}
